AWSTemplateFormatVersion: '2010-09-09'
Description: Basic CloudFormation Template - S3 + EC2

Parameters:
  KeyName:
    Description: EC2 Key Pair to SSH
    Type: AWS::EC2::KeyPair::KeyName

Resources:

  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "workshop-demo-bucket-${AWS::AccountId}"

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      ImageId: ami-0f5ee92e2d63afc18  # Amazon Linux 2023 (ap-south-1)
      SecurityGroupIds:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: WorkshopEC2

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref MyS3Bucket

  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref MyEC2Instance
